Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      VpcId: vpc-c392afab
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0

Outputs:
  Securitygroup:
    Description: The security group ID to use for public web servers
    Value:
      Fn::GetAtt: 
        - InstanceSecurityGroup
        - GroupId
    Export:
      Name: !Sub "${AWS::StackName}-SecurityGroup"
